version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    cooldown:
      default-days: 7
    groups:
      oxlint:
        patterns:
          - "oxlint"
          - "oxfmt"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    cooldown:
      default-days: 7
